### ISSUE TITLE
Data source: AMP

### ISSUE THREAD

**Issue by mayrop** [analytics-debugger/google-analytics-4-for-amp#3]
First of all, this project is amazing, thank you!

This is more a question than a bug, is [data source](https://github.com/analytics-debugger/google-analytics-4-for-amp/blob/main/ga4.json#L73) reported by GA4? I know universal uses it in Users: Data Source but I can't find it in GA4.

I modified the requests to include it as a parameter:
```
    "requests": {
        ...
        "ga4Pageview": {
            "baseUrl": "/g/collect?${ga4SharedPayload}&en=page_view&ep.data_source=${dataSource}"
        },        
        "ga4Event": {
            "baseUrl": "/g/collect?${ga4SharedPayload}&en=${eventName}&ep.data_source=${dataSource}"
        }
        ...
    }
```

**Comment by thyngster** [comment]
No, it's not reported actually. It was just added to easily filter the hits while debugging and in the hypothetic case Google adds that internal dimension in the future. I would that maybe the ideal setup would be tracking AMP with a different stream and then build a rollup ( but that's for 360 users )

This library "tries" to provide support for tracking GA4 on AMP and any customization over the custom event parameters / user properties needs to be done by the users, since not everyone may want to have that parameter. :)

**Comment by mayrop** [comment]
Makes sense, thanks again for this!
