### ISSUE TITLE
fix for the type as current one won't work

### ISSUE THREAD

**Issue by Hasan0ff** [analytics-debugger/google-analytics-4-for-amp#32]
Hey David,

First of all, amazing work. I searched around and found your fix to the G4 problem. However, there is a slight problem with your code and it won't work for anyone.  I didn't know how to contact you so i'm writing here, and please do change the README.md

The main reason for this code not to work is the type problem. On official amp.dev website it is mentioned that we have to use type=gtag. I did change that on my website and everything began to work smoothly.

`<amp-analytics  type="gtag"  config="https://amp.analytics-debugger.com/ga4.json"  data-credentials="include">`

Once again, thanks for the amazing work and best of luck!

**Comment by thyngster** [comment]
@Hasan0ff that affirmation is not correct at all . The docs are right. Both works in any, since "gtag" will just relay on the same stuff as "googleanalytics" . Atm there're 900M unique users just relying on the CDN. I can tell you the docs are rights.  If that wasn't working for your I'm sure there was someone else at your end messing up things.

**Comment by thyngster** [comment]
Working demo: https://amp.analytics-debugger.com/demo/
